
networks:
  webapp:
name: combs_and_clippers
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: iamaqim/combs_and_clippers-backend
    container_name: combs_and_clippers-php
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/confd/local.ini:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - combs_and_clippers_vendor:/var/www/vendor
      - combs_and_clippers_node_modules:/var/www/node_modules
    ports:
      - "8009:80"
    networks:
      - webapp
  mysql:
      container_name: combs_and_clippers_mysql
      image: mysql:8.0
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: combs_and_clippers
      volumes:
          - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:rw
          - combs_and_clippers_dbdata:/var/lib/mysql
      ports:
          - 53310:3306
      networks:
        - webapp
  phpmyadmin:
      image: phpmyadmin:latest
      environment:
        - PMA_ARBITRARY=1
      volumes:
          - ./docker/php/php.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
          - combs_and_clippers_phpmyadmindata:/usr/src/phpmyadmin
      ports:
          - 8008:80
      depends_on:
          - mysql
      networks:
        - webapp
volumes:
  combs_and_clippers_phpmyadmindata:
  combs_and_clippers_dbdata:
  combs_and_clippers_vendor:
  combs_and_clippers_node_modules: